
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label NumOfCatLabel;

	private global::Gtk.SpinButton NumOfCatButton;

	private global::Gtk.VBox vboxCategories;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label USBPortLabel;

	private global::Gtk.Entry entryUSBPort;

	private global::Gtk.Button LoadButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Flashcards App");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.NumOfCatLabel = new global::Gtk.Label();
		this.NumOfCatLabel.Name = "NumOfCatLabel";
		this.NumOfCatLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Number Of Categories:");
		this.hbox1.Add(this.NumOfCatLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.NumOfCatLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.NumOfCatButton = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.NumOfCatButton.CanFocus = true;
		this.NumOfCatButton.Name = "NumOfCatButton";
		this.NumOfCatButton.Adjustment.PageIncrement = 10D;
		this.NumOfCatButton.ClimbRate = 1D;
		this.NumOfCatButton.Numeric = true;
		this.NumOfCatButton.Value = 1D;
		this.NumOfCatButton.Wrap = true;
		this.hbox1.Add(this.NumOfCatButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.NumOfCatButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vboxCategories = new global::Gtk.VBox();
		this.vboxCategories.Name = "vboxCategories";
		this.vboxCategories.Spacing = 6;
		this.vbox1.Add(this.vboxCategories);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vboxCategories]));
		w4.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.vbox1.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vseparator1]));
		w5.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.USBPortLabel = new global::Gtk.Label();
		this.USBPortLabel.Name = "USBPortLabel";
		this.USBPortLabel.LabelProp = global::Mono.Unix.Catalog.GetString("USB Serial Port:");
		this.hbox3.Add(this.USBPortLabel);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.USBPortLabel]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entryUSBPort = new global::Gtk.Entry();
		this.entryUSBPort.CanFocus = true;
		this.entryUSBPort.Name = "entryUSBPort";
		this.entryUSBPort.IsEditable = true;
		this.entryUSBPort.InvisibleChar = '•';
		this.hbox3.Add(this.entryUSBPort);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryUSBPort]));
		w7.Position = 1;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.LoadButton = new global::Gtk.Button();
		this.LoadButton.CanFocus = true;
		this.LoadButton.Name = "LoadButton";
		this.LoadButton.UseUnderline = true;
		this.LoadButton.Label = global::Mono.Unix.Catalog.GetString("Load");
		this.vbox1.Add(this.LoadButton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.LoadButton]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 543;
		this.DefaultHeight = 499;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
